In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('sepsis3-df.csv')

In [5]:
df[df.excluded == 0]

,icustay_id,hadm_id,excluded,intime,outtime,dbsource,suspected_infection_time_poe,suspected_infection_time_poe_days,specimen_poe,positiveculture_poe,...,sepsis_cdc_simple,elixhauser_hospital,vent,sofa,lods,sirs,qsofa,qsofa_sysbp_score,qsofa_gcs_score,qsofa_resprate_score
0,200021,109307,0,2114-12-26 19:45:12,2114-12-27 22:46:28,metavision,NaN,NaN,NaN,NaN,...,0,4,1,4,7,3,3,1.0,1.0,1.0
1,200028,181955,0,2133-10-29 17:13:50,2133-11-01 14:55:14,metavision,NaN,NaN,NaN,NaN,...,0,8,1,10,6,3,2,1.0,0.0,1.0
2,200033,198650,0,2198-08-07 17:56:17,2198-08-21 14:59:18,metavision,2198-08-08 01:00:00,-0.294248,MRSA SCREEN,0.0,...,1,5,0,1,1,2,0,0.0,0.0,0.0
3,200061,121149,0,2134-01-23 16:38:46,2134-01-25 16:59:14,metavision,2134-01-24 00:00:00,-0.306412,BLOOD CULTURE,0.0,...,0,6,0,2,2,4,1,0.0,0.0,1.0
4,200075,132255,0,2159-09-23 00:13:20,2159-09-25 01:55:17,metavision,2159-09-23 00:00:00,0.009259,MRSA SCREEN,0.0,...,1,10,1,8,4,3,2,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11320,299948,183226,0,2119-05-25 13:47:31,2119-05-27 12:31:54,metavision,2119-05-25 14:37:00,-0.034363,MRSA SCREEN,0.0,...,1,-4,0,3,2,2,2,1.0,0.0,1.0
11321,299949,199962,0,2118-07-16 05:42:45,2118-07-20 14:46:25,metavision,2118-07-16 00:00:00,0.238021,SWAB,0.0,...,0,-5,1,3,2,2,0,0.0,0.0,0.0
11322,299950,110990,0,2122-06-20 13:25:29,2122-06-22 18:21:02,metavision,2122-06-20 00:00:00,0.559363,URINE,0.0,...,1,4,0,5,2,2,2,1.0,0.0,1.0
11323,299962,146497,0,2195-11-25 19:04:06,2195-11-26 13:21:12,metavision,NaN,NaN,NaN,NaN,...,0,0,0,5,6,2,2,1.0,0.0,1.0
11324,299998,158288,0,2181-07-05 18:47:40,2181-07-07 17:24:38,metavision,2181-07-05 00:00:00,0.783102,MRSA SCREEN,0.0,...,1,8,1,4,5,1,1,1.0,0.0,0.0